name: Build OpenSSL (Windows VS2026)
 
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
 
jobs:
  build:
    runs-on: windows-latest
    env:
      OPENSSL_VERSION: openssl-3.0.15
    strategy:
      matrix:
        arch: [x86, x64]
        config: [Release, Debug]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Perl
        run: choco install strawberryperl -y

      - name: Install NASM
        run: choco install nasm -y

      - name: Download OpenSSL
        run: |
          curl -LO https://www.openssl.org/source/$env:OPENSSL_VERSION.tar.gz
          tar -xf "$env:OPENSSL_VERSION.tar.gz"

      - name: Setup MSVC (VS2026)
        uses: ilammy/msvc-dev-cmd@v1 # Update to VS2026 when action is available
        with:
          arch: ${{ matrix.arch }}

      - name: Configure OpenSSL
        working-directory: ${{ env.OPENSSL_VERSION }}
        run: |
          $target = if ("${{ matrix.arch }}" -eq "x64") { "VC-WIN64A" } else { "VC-WIN32" }
          $debugFlag = if ("${{ matrix.config }}" -eq "Debug") { "--debug" } else { "--release" }
          $prefix = "${{ github.workspace }}/openssl-install-${{ matrix.arch }}-${{ matrix.config }}"
          perl Configure $target shared no-autoload-config $debugFlag --prefix=$prefix

      - name: Build OpenSSL
        working-directory: ${{ env.OPENSSL_VERSION }}
        run: nmake

      - name: Install OpenSSL
        working-directory: ${{ env.OPENSSL_VERSION }}
        run: nmake install

      - name: Upload OpenSSL binaries
        uses: actions/upload-artifact@v4
        with:
          name: openssl-windows-${{ matrix.arch }}-${{ matrix.config }}
          path: openssl-install-${{ matrix.arch }}-${{ matrix.config }}